### ISSUE TITLE
Please publish a version to PyPi

### ISSUE THREAD

**Issue by scheidtdav** [DAMEK86/pykostal#3]
Hey @DAMEK86 ,

any chance you can push a new version of this to PyPi?
I am testing recent changes inside Home Assistant (since I do want the statistics feature of HA to work with the integration) and I think the library is ready to get the component started.

Let me know if there is anything required to get it published.
Thanks in advance!

**Comment by DAMEK86** [comment]
version bumped to 0.0.2

if you need a special version, pls let me know.
